# Site settings
title: Octanis
email: info@octanis.org
description: "Octanis is an open incubator with the objective to distill its findings into pragmatic solutions and inventions, accessible to everyone."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://octanisorg.github.io" # the base hostname & protocol for your site
twitter_username: octanisorg
github_username:  octanisorg


# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :nested


gems:
- jekyll-gallery-generator

gallery:
  dir: photos               # Path to the gallery
  symlink: true            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: ""  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 600                  # max width of thumbnails (in pixels)
    y: 600                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    STIL17:
      best_image: IMG_5140.jpg  # The image to show on the gallery index page. Defaults to the last image.
